version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bodya
      - MONGO_INITDB_ROOT_PASSWORD=bodya
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=bodya
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bodya
      - ME_CONFIG_MONGODB_URL=mongodb://bodya:bodya@mongodb:27017/
  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  cache:
    driver: local
  mongo: {}
  esdata1:
    driver: local
  esdata2:
    driver: local
  db:
    driver: local

networks:
  esnet: